import { Hero } from '../app/models/hero.model';

export const HEROES: Hero[] = [
  { id: 1,
    name:'Izuku Midoriya',
    alias: 'Deku',
    quirk: 'One for All',
    imagePath: 'https://upload.wikimedia.org/wikipedia/en/d/db/Izuku_Midoriya_%28My_Hero_Academia_character%29.png',
    class: '1-A' },
  { id: 2,
    name: 'Bakugo',
    alias: 'Dynamight ',
    quirk: 'Explosion',
    imagePath: 'https://upload.wikimedia.org/wikipedia/en/0/02/BakugoMHAVol13.png',
    class: '1-A' },
  { id: 3,
    name: 'Ochaco Uraraka',
    alias:'Uravity ',
    quirk: 'Zero Gravity ',
    imagePath: 'https://static.wikia.nocookie.net/bokunoheroacademia/images/6/69/Ochaco_School_Uniform_Full_Body.png/revision/latest?cb=20190215054343',
    class: '1-A' },
  { id: 4,
    name: 'Toshinori Yagi',
    alias: 'Allmight',
    quirk: 'One for All',
    imagePath: 'https://static.wikia.nocookie.net/bokunoheroacademia/images/c/cd/Toshinori_Yagi_Golden_Age_Hero_Costume_%28Anime%29.png/revision/latest/scale-to-width-down/311?cb=20190129015644',
    },
  { id: 5,
    name: 'Tsuyu Asui ',
    alias: 'Rainy Season Hero: Froppy ',
    quirk: 'Frog',
    imagePath: 'https://static.wikia.nocookie.net/bokunoheroacademia/images/d/dc/Tsuyu_Asui_School_Uniform.png/revision/latest/scale-to-width-down/214?cb=20160118114942',
    class: '1-A'},
];