import { Hero } from '../app/models/hero.model';

export const HEROES: Hero[] = [
  { id: 1,
    name:'Izuku Midoriya',
    alias: 'Deku',
    quirk: 'One for All',
    imagePath: '/assets/images/deku.png',
    class: '1-A' },
  { id: 2,
    name: 'Bakugo Katsuki',
    alias: 'Dynamight ',
    quirk: 'Explosion',
    imagePath: '/assets/images/bakugo.png',
    class: '1-A' },
  { id: 3,
    name: 'Ochaco Uraraka',
    alias:'Uravity ',
    quirk: 'Zero Gravity ',
    imagePath: '/assets/images/uravity.png',
    class: '1-A' },
  { id: 4,
    name: 'Toshinori Yagi',
    alias: 'Allmight',
    quirk: 'One for All',
    imagePath: '/assets/images/All_Might_baraque.png',
    },
  { id: 5,
    name: 'Tsuyu Asui ',
    alias: 'Rainy Season Hero: Froppy ',
    quirk: 'Frog',
    imagePath: '/assets/images/froppy.png',
    class: '1-A'},
];